url: "https://AndrzejRuprecht.github.io"
baseurl: ""

title: Andrzej L. Ruprecht Official Website

description: Andrzej L. Ruprecht, Ph.D., Polish scientist.

author:
  name: Michal T. Ruprecht

url-pretty: "AndrzejRuprecht.github.io"

gtag: "'config', 'UA-141203061-1'"

google_analytics: "UA-141203061-1"

exclude:
  - CHANGELOG.md
  - CNAME
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Vagrantfile

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
